### ISSUE TITLE
Sitemap is generated in the current directory, rather than using $MWK

### ISSUE THREAD

**Issue by opcon** [a3n/miki#1]
Line https://github.com/a3n/miki/blob/master/makefile#L145 has a bug, I think it should be:

```
tree -H $(MWK) -T "$(MWK) sitemap" $(MWK) > $@
```

to ensure that `tree` is run on the `$MWK` directory :+1:

**Comment by a3n** [comment]
I'm not seeing that behavior, after a few test runs. I'll keep looking.


What's the output of



echo $MWK



on your system?



Are you using Gnu Make?



$ make --version

GNU Make 4.1

...



Here's my test:



aaron@tesla ~/MyMiki % 

rm sitemap.html



aaron@tesla ~/MyMiki %

cd



aaron@tesla ~ %

pwd

/home/aaron



aaron@tesla ~ %

mwk



# Generate sitemap.

#

tree -H /home/aaron/MyMiki -T "/home/aaron/MyMiki sitemap" >
/home/aaron/MyMiki/sitemap.html




Notice in the expanded makefile output, the result is redirected to
/home/aaron/MyMiki, which is the directory where my example wiki is.


I also tested this on my actual personal wiki and got the
expected behavior.


Did you update your clone from the remote, or did you manually copy
lines into your existing makefile (total guess).


On my system:



$ grep -i site makefile

SITE := $(MWK)/sitemap.html

HTML := $(RHTML) $(MHTML) $(CATA) $(SITE)

# Generate sitemap

sitemap: $(SITE)

$(SITE):

        # Generate sitemap.

        tree -H $(MWK) -T "$(MWK) sitemap" > $@



If I just run the tree command on the command line, without the
redirection (and remove the parens around the two instances of MWK),
then the sitemap is printed in the terminal.


The line in the makefile is redirected to $@, which is $(SITE), which is
defined in the first line in the grep output above as <in the
wiki>/sitemap.hmtl. It's hard to see how the output could go anywhere
except where it's supposed to.






On Tue, 14 Mar 2017 22:22 -0700, Patrick Yates <notifications@github.com> wrote:
> Line https://github.com/a3n/miki/blob/master/makefile#L145 has a bug,
> I think it should be:


> tree -H $(MWK) -T "$(MWK) sitemap" $(MWK) > $@
>
> to ensure that tree is run on the $MWK directory 👍



> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
> 



--

Aaron




Links:

  1. https://github.com/a3n/miki/issues/1

**Comment by opcon** [comment]
Sorry, I think I didn't explain my problem clearly in the first post. The `sitemap.html` is generated fine in the `$MWK` directory, that is not a problem.

The problem is that `tree` generates the directory tree for the current working directory, which is wherever the `mwk` command is run from. Instead I think that the tree should be generated for the `$MWK` directory.

**Comment by a3n** [comment]
Ah, you are correct in the report and the fix.



Fixed and pushed, thanks very much.





On Tue, 14 Mar 2017 23:12 -0700, Patrick Yates <notifications@github.com> wrote:
> Sorry, I think I didn't explain my problem clearly in the first post.
> The sitemap.html is generated fine in the $MWK directory, that is not
> a problem.
> The problem is that tree generates the directory tree for the current
> working directory, which is wherever the mwk command is run from.
> Instead I think that the tree should be generated for the $MWK
> directory.
> — You are receiving this because you were assigned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].
> 



--

Aaron


Links:

  1. https://github.com/a3n/miki/issues/1#issuecomment-286650427

**Comment by a3n** [comment]
Closing issue as fixed.
